SELECT * FROM DuLieu.HOCVIEN;
SELECT * FROM DuLieu.DIEMDANH
SELECT * FROM DuLieu.HOCTAP
SELECT * FROM DuLieu.NHANVIEN;
SELECT * FROM DuLieu.GIAOVIEN;
SELECT * FROM DuLieu.PHANCONG;

UPDATE DuLieu.HOCVIEN
SET HOTENHV = 'Truong Van Nghia'
WHERE MAHV = 'HV008';

select MABT, HOCTAP.MAHV, HOTENHV, DIEM, DIEMTOIDA, LOPHOCPHAN.MALOPHP from DuLieu.HOCVIEN, DuLieu.HOCTAP, DuLieu.LOPHOCPHAN, DuLieu.PHANCONG where HOCVIEN.MAHV = HOCTAP.MAHV and HOCTAP.MALOPHP = LOPHOCPHAN.MALOPHP AND LOPHOCPHAN.MALOPHP = PHANCONG.MALOPHP AND MAGV = 'GV001';